name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    name: ${{matrix.name || format('Rust {0}', matrix.rust)}}
    runs-on: ${{matrix.os || 'ubuntu'}}-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - rust: stable
          - rust: beta
          - rust: nightly
          - rust: 1.56.0
          - name: macOS
            os: macos
            rust: stable
          - name: Windows
            os: windows
            rust: stable
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          profile: minimal
          override: true
      - run: cargo build
      - run: cargo test
      - run: cargo test --no-default-features
      - run: cargo test --features "openssl_tests"

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
          profile: minimal
          override: true
      - run: cargo clippy --tests -- -Dclippy::all

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
          profile: minimal
          override: true
      - run: cargo fmt --check

  doc:
    name: Doc
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rust-docs
          profile: minimal
          override: true
      - run: cargo doc --no-deps --all-features

  no-std:
    name: Build no-std
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: thumbv6m-none-eabi
          profile: minimal
          override: true
      - run: cargo build --no-default-features --target thumbv6m-none-eabi
